flowcode_user_api_login:     
    resource: Flowcode\UserBundle\Controller\Api\SecurityController
    type:     rest
    
flowcode_user_api_login_v2:     
    resource: Flowcode\UserBundle\Controller\Api\SecurityControllerV2
    type:     rest