flowcode_user_api_login:     
    path: /login_check
    defaults:  { _controller: FlowcodeUserBundle:Api\User:check }
    methods: [POST]
    
flowcode_user_api_register:     
    path:     /users/register     
    defaults: { _controller: FlowcodeUserBundle:Api\User:register }     
    methods:  [POST] 