parameters:
    form.type.user_register.api.class: Flowcode\UserBundle\Form\Api\UserRegisterType   
    form.type.user_forgot.api.class: Flowcode\UserBundle\Form\Api\UserForgotType   
    form.type.user_recover.api.class: Flowcode\UserBundle\Form\Api\UserRecoverType   


services:
    form.type.user:
        class: Flowcode\UserBundle\Form\UserType
        arguments: ["@security.token_storage"]
        tags:
            - { name: form.type, alias: user_type }

    form.type.user_profile:
        class: Flowcode\UserBundle\Form\UserProfileType
        arguments: ["@security.token_storage"]
        tags:
            - { name: form.type, alias: flowcode_userbundle_user_profile }

    form.type.user_register:
        class: Flowcode\UserBundle\Form\UserRegisterType
        arguments: ["@security.token_storage"]
        tags:
            - { name: form.type, alias: user_register_type }
            
    form.type.user_register.api:
        class: "%form.type.user_register.api.class%"
        arguments: ["%flowcode.model.user.class%"]
        tags:
            - { name: form.type, alias: user_register_type_api }
            
    form.type.user_forgot.api:
        class: "%form.type.user_forgot.api.class%"
        arguments: ["%flowcode.model.user.class%"]
        tags:
            - { name: form.type, alias: user_forgot_type_api }
            
    form.type.user_recover.api:
        class: "%form.type.user_recover.api.class%"
        arguments: ["%flowcode.model.user.class%"]
        tags:
            - { name: form.type, alias: user_recover_type_api }
            
    flowcode.user.notification:
        class: Flowcode\UserBundle\Service\UserNotificationService
        arguments: ["@service_container", "@flowcode.sender.senderEmailMailgun", "@templating"]

    flowcode.user.repository:         
        class: Doctrine\ORM\EntityRepository         
        factory: ["@doctrine.orm.entity_manager", getRepository]         
        arguments:             
            - "%flowcode.model.user.class%"

    flowcode.user.group.repository:         
        class: Doctrine\ORM\EntityRepository         
        factory: ["@doctrine.orm.entity_manager", getRepository]         
        arguments:             
            - "%flowcode.model.user.group.class%"
            
    flowcode.role.repository:         
        class: Doctrine\ORM\EntityRepository         
        factory: ["@doctrine.orm.entity_manager", getRepository]         
        arguments:             
            - "%flowcode.model.role.class%"
            
    flowcode.user:
        class: Flowcode\UserBundle\Service\UserService
        arguments: ["@doctrine.orm.entity_manager", "@security.password_encoder", "@service_container", "@security.token_storage", "@event_dispatcher", "@flowcode.user.repository", "%flowcode.model.user.class%"]

    flowcode.user.group:
        class: Flowcode\UserBundle\Service\UserGroupService
        arguments: ["@doctrine.orm.entity_manager", "@service_container", "@flowcode.user.group.repository", "%flowcode.model.user.group.class%"]
    
    flowcode.role:
        class: Flowcode\UserBundle\Service\RoleService
        arguments: ["@doctrine.orm.entity_manager", "@service_container", "@flowcode.role.repository", "%flowcode.model.role.class%"]
