parameters:
    form.type.user_register.api.class: Flowcode\UserBundle\Form\Api\UserRegisterType   
    flowcode.model.user.class: Flowcode\UserBundle\Entity\DummyUser

services:
    form.type.user:
        class: Flowcode\UserBundle\Form\UserType
        arguments: ["@security.token_storage"]
        tags:
            - { name: form.type, alias: user_type }

    form.type.user_profile:
        class: Flowcode\UserBundle\Form\UserProfileType
        arguments: ["@security.token_storage"]
        tags:
            - { name: form.type, alias: flowcode_userbundle_user_profile }

    form.type.user_register:
        class: Flowcode\UserBundle\Form\UserRegisterType
        arguments: ["@security.token_storage"]
        tags:
            - { name: form.type, alias: user_register_type }
            
    form.type.user_register.api:
        class: Flowcode\UserBundle\Form\Api\UserRegisterType
        arguments: [%flowcode.model.user.class%]
        tags:
            - { name: form.type, alias: user_register_type_api }

    amulen.user.notification:
        class: Flowcode\UserBundle\Service\UserNotificationService
        arguments: ["@service_container", "@flowcode.sender.senderEmailLocal", "@templating"]

    flowcode.user:
        class: Flowcode\UserBundle\Service\UserService
        arguments: ["@doctrine.orm.entity_manager", "@security.password_encoder", "@service_container", "@security.token_storage", "@event_dispatcher", %flowcode.model.user.class%]
