App\UserBundle\Entity\User:
    properties:
        firstname:
            - NotNull: ~
            - Length:
                min: 2
                max: 50
                minMessage: "Your title must be at least  characters length"
                maxMessage: "Your title name cannot be longer than  characters length"
        lastname:
            - NotNull: ~
            - Length:
                min: 2
                max: 50
                minMessage: "Your title must be at least  characters length"
                maxMessage: "Your title name cannot be longer than  characters length"
        status:
            - NotNull: ~
